### ISSUE TITLE
Is this project actively maintained? Also officially/community?

### ISSUE THREAD

**Issue by chrisK824** [GoogleCloudPlatform/appengine-python-standard#116]

**Comment by ludoch** [comment]
Do you have something in mind? This project is officially supported for AppEngine Python product.

You can see the support lifecycle info for Python Runtime at:
https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#python
See support for latest Python 3.12 until 2028 for example.
New releases will also be supported in the future.

**Comment by chrisK824** [comment]
Thanks both of you!
