### ISSUE TITLE
Need to be able to use compatible protocol for deferred

### ISSUE THREAD

**Issue by sadovnychyi** [GoogleCloudPlatform/appengine-python-standard#31]
Similar to `NDB_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL` and `MEMCACHE_USE_CROSS_COMPATIBLE_PROTOCOL`, otherwise tasks created on python3 fail on python2 (unless we monkeypatch).

**Comment by asriniva** [comment]
`DEFERRED_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL` env var can now be set to get this to work.
