### ISSUE TITLE
Django: Attempted RPC call without active security ticket 

### ISSUE THREAD

**Issue by cls-sigma** [GoogleCloudPlatform/appengine-python-standard#58]
I am using django instead of flask, I put in wsgi.py the following code

#from .wsgi import application
from google.appengine.api import wrap_wsgi_app
app=wrap_wsgi_app(application, use_legacy_context_mode=True,use_deferred=False)

and my  app.yaml:

runtime: python39
entrypoint: gunicorn -b :$PORT youtube.wsgi #name of my django project: youtube
app_engine_apis : true

I deploy it with  "gcloud beta app deploy"

And if i do
 
def song(temps):
   time.spleep(temps)
   return "Done"

temps=100
e=background_thread.start_new_background_thread(song, [f"{temps}"]) 
 
But i get an error like:
  Attempted RPC call without active security ticket

Request Method: | POST
https://django-deploy........com/download/new/
3.2.8
RPCFailedError
Attempted RPC call without active security ticket
/layers/google.python.pip/pip/lib/python3.9/site-packages/google/appengine/runtime/default_api_stub.py, line 182, in _MakeCallImpl
/opt/python3.9/bin/python3
3.9.13
['/workspace',  '/layers/google.python.pip/pip/bin',  '/opt/python3.9/lib/python39.zip',  '/opt/python3.9/lib/python3.9',  '/opt/python3.9/lib/python3.9/lib-dynload',  '/layers/google.python.pip/pip/lib/python3.9/site-packages',  '/opt/python3.9/lib/python3.9/site-packages']

Help me please. Every suggest will be welcome

- Version: python3.9
- Platform: DJANGO on appengine

**Comment by shreejad** [comment]
This should be fixed after GA (March 2022).
Please make sure:
- gcloud is on the latest version
- `gcloud app deploy` is used (no need for beta now)
- `app.yaml` has `app_engine_apis: true`
