### ISSUE TITLE
Plans for future remote_api support?

### ISSUE THREAD

**Issue by alexjoeyyong** [GoogleCloudPlatform/appengine-python-standard#59]
## Expected Behavior
`from google.appengine.ext.remote_api import remote_api_stub` works like in the python2 version of this. 

I see references to the remote_api_stub in the test bed like here:
https://github.com/GoogleCloudPlatform/appengine-python-standard/blob/cc19a2edb1907a8b91c6fb190760ade6ae249a08/src/google/appengine/ext/testbed/__init__.py

## Actual Behavior
remote_api_stub is not available. 

## Steps to Reproduce the Problem

1. run `from google.appengine.ext.remote_api import remote_api_stub` 
This will fail.
I'm trying to run code like:
```
remote_api_stub.ConfigureRemoteApiForOAuth(
      host,
      path,
      app_id=app_id,
      secure=secure
    )
```
    
  
    
```
    remote_api_stub.ConfigureRemoteApi(
    app_id=app_id,
    path=path,
    auth_func=lambda: ('test@company.com, None),
    servername=host,
    secure=secure
  )
```

Is there a better way to do this now with the legacy bundle? Or something else?

## Specifications

- Version:  SDK 392.0.0  and appengine-python-standard 1.0.0
- Platform: python39

**Comment by embray** [comment]
I've also been searching around to find out what the suitable replacement is for this.  I believe we can use the standard NDB client but it's not at all obvious how to use that as a replacement for remote_api_stub, so some guidance would be much appreciated.

**Comment by alexjoeyyong** [comment]
@embray yeah, so far I haven't had to do anything fancy to use it. I removed the references to remote_api_stub myself, didn't add anything new in, and everything JustWorked™.  

So it looks like that the functionality was folded into the legacy bundles. 

@asriniva @myelin @shreejad @wescpy is that correct?  If so, could we get documentation mentioning this fact for future folks curious about remote api stuff with the legacy bundle?

**Comment by embray** [comment]
Strange, I can't get it to work.  For example, without explicitly setting up the remote API stub it's not clear how to connect to a local dev server from a shell.

**Comment by mlarkin00** [comment]
The remote_api was created to allow App Engine apps to access resources in other apps (this was back before GCP, and GCP Projects, existed).  Now, an App Engine app can access resources in other Projects (apps) by using the relevant client libraries.  For example, if you used the remote_api to access Datastore in a different app/project, you can use either the [Datastore client libraries](https://cloud.google.com/datastore/docs/reference/libraries) or [Cloud NDB](https://cloud.google.com/appengine/docs/standard/python3/migrating-to-cloud-ndb#key_differences), both of which allow you to specify a target instance in another project.

There are no plans to support the remote_api as part of this SDK.

**Comment by pnico** [comment]
@alexjoeyyong can you describe what you were doing before that relied on remote_api_stub and how you got it to work without it? Were you using `ConfigureRemoteApiForOAuth` or `ConfigureRemoteApi` as @embray describes in the issue? If so, can you give an example of how to achieve the same result without these?
