### ISSUE TITLE
ndb.key.urlsafe() should return a string not bytes

### ISSUE THREAD

**Issue by martin-green** [GoogleCloudPlatform/appengine-python-standard#71]
## Expected Behavior
When calling ndb.key.urlsafe() you should get a string that can be concatenated with other strings. 

## Actual Behavior
Currently it return bytes so you need to add .decode() on every call to urlsafe()

## Steps to Reproduce the Problem

1. On a ndb.Model derived class do:  x.key.urlsafe() + '\'
2. this will generate a runtime error: TypeError: can only concatenate str (not "bytes") to str

## Specifications

- Version: 1.0.0
- Platform: Ubuntu 20.04 (wsl2)

**Comment by spiqueras** [comment]
Particularly annoying when serializing to JSON.

Will it remain a `bytes` object or will it be changed to `str`? I have some .`decode()`s to add.

**Comment by martin-green** [comment]
It is very annoying. Without this you would have to change all templates with string variables (almost all).

**Comment by shreejad** [comment]
Hi, we had an internal discussion about this behavior, and we usually try to align with Cloud NDB. This would be a breaking change, so the barrier is high. I will discuss with the Cloud NDB team and post an update. For now, I don't see this change happening in the short term future.
